default:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: dbt
      pass: password1
      dbname: snowdepth
      schema: snowdepth
  target: dev